/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package smartvpn/backend */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 5 "android_bridge.go"

#include <stdlib.h>

// The JNI side lives in android_jni_android.c, so that the Go side deals in
// strings and integers and never in a JNIEnv. These are the calls that go the
// other way: sealing a secret with the Android keystore, and protecting a socket
// so the kernel's own connections do not re-enter the tunnel they carry.
int smartvpn_bridge_init(const char *className);
int smartvpn_protect(int fd);
char *smartvpn_seal(const char *plain);
char *smartvpn_open(const char *sealed);
void smartvpn_drop_tunnel(void);
char *smartvpn_describe_tunnel(void);

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// SmartVPNStart is the first thing the Java side calls: it prepares the profile
// and starts the local API, and answers with the address the window needs. The
// answer is a bootstrap record as JSON — the same one the Windows service
// prints for its window — so that a refusal travels back as a reason rather
// than as a port that never arrives.
//
extern char* SmartVPNStart(char* dataDir, char* bridgeClass);

// SmartVPNStop ends the service and the connection with it.
//
extern void SmartVPNStop();

// SmartVPNSetTunnel records the tunnel the VpnService established, or reports
// that it is gone.
//
// The tunnel is the user's to turn on and off, and the system's to take away:
// turning the VPN off from the system's own settings screen stops this app's
// VpnService without the window being involved. A kernel left running against a
// descriptor that no longer exists would look connected while carrying nothing,
// so losing the tunnel ends the connection rather than being recorded as a
// detail.
//
extern char* SmartVPNSetTunnel(int authorized, int fd, char* info);

#ifdef __cplusplus
}
#endif
